---
title: "Day 2 (August 1, 2024)"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
  @import url('https://fonts.googleapis.com/css2?family=Public+Sans&display=swap');

  body {
    font-family: 'Public Sans', sans-serif;
  }

  .agenda-table {
    width: 100%;
    border-collapse: collapse;
  }

  .agenda-table th, .agenda-table td {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: left;
  }

  .agenda-table th {
    background-color: #f4f4f4;
    color: #333;
  }

  .agenda-table td a {
    color: #23408F; /* Matching the color used for headers */
  }

  .agenda-table .session-time {
    width: 15%; /* Adjust the width of the Time column */
  }

  .break-row {
    background-color: #e0f4f9; /* Light blue color specifically for break rows */
  }
  
  .agenda-table tbody tr:nth-child(odd):not(.break-row) {
    background-color: #f9f9f9; /* Apply grey shading only to non-break odd rows */
  }
</style>

## Agenda

<table class="agenda-table">
  <thead>
    <tr>
      <th>Time</th>
      <th>Session Title</th>
      <th>Description</th>
      <th>Speakers/Moderators</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="session-time">8:30 AM - 9:30 AM</td>
      <td>Public Data Resources</td>
      <td>Overview of publicly available data resources related to food price inflation, including BLS Consumer Price Index (CPI), USDA Food-at-Home Monthly Area Prices (F-MAP), and BEA Personal Consumer Expenditures (PCE). How to access and utilize these resources effectively.</td>
      <td><a href="speakers/reed.html" target="_blank">Steve Reed</a>, <a href="speakers/sweitzer.html" target="_blank">Megan Sweitzer</a>, <a href="speakers/aizcorbe.html" target="_blank">Ana Aizcorbe</a></td>
    </tr>
    <tr class="break-row">
      <td class="session-time">9:30 AM - 9:45 AM</td>
      <td>Break</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="session-time">9:45 AM - 10:45 AM</td>
      <td>Private Data Collection and Research</td>
      <td>Presentation from industry experts on private data collection methods and their contribution to understanding food price trends. Discussion on the challenges and opportunities in utilizing private data for research purposes.</td>
      <td><a href="speakers/thomas.html" target="_blank">Catherine Cullinane-Thomas</a>, <a href="speakers/muth.html" target="_blank">Mary Muth</a>, <a href="speakers/feler.html" target="_blank">Leo Feler</a>, <a href="speakers/edmonds.html" target="_blank">Doug Edmonds</a></td>
    </tr>
    <tr>
      <td class="session-time">10:45 AM - 12:00 PM</td>
      <td><a href="topics.html" target="_blank">Breakout Sessions</a></td>
      <td>Participants will be divided into smaller groups to discuss and identify stakeholders’ needs, underutilized information, and potential improvements in evaluating and forecasting food prices.</td>
      <td>Facilitators include: <a href="speakers/aizcorbe.html" target="_blank">Ana Aizcorbe</a>, <a href="speakers/baffes.html" target="_blank">John Baffes</a>, <a href="speakers/bayham.html" target="_blank">Jude Bayham</a>, <a href="speakers/byrne.html" target="_blank">Anne Byrne</a>, <a href="speakers/cakir.html" target="_blank">Metin Çakir</a>, <a href="speakers/kroetz.html" target="_blank">Kailin Kroetz</a>, <a href="speakers/macdonald.html" target="_blank">James MacDonald</a>, <a href="speakers/maclachlan.html" target="_blank">Matthew Maclachlan</a>, <a href="speakers/okrent.html" target="_blank">Abigail Okrent</a>, <a href="speakers/smith.html" target="_blank">Aaron Smith</a>, <a href="speakers/somogyi.html" target="_blank">Simon Somogyi</a>, and <a href="speakers/zhen.html" target="_blank">Chen Zhen</a></td>
    </tr>
    <tr>
      <td class="session-time">12:00 PM - 12:30 PM</td>
      <td>Closing Remarks</td>
      <td>Recap of the workshop and information about the upcoming <a href="journal.html" target="_blank">special issue</a>.</td>
      <td></td>
    </tr>
  </tbody>
</table>



<!--
## Agenda

| Time | Description | Speakers/Moderators | 
|----------------------|---------------------------------------------|------------------------------------------|
| 8:00 AM - 8:30 AM    | Registration and Coffee                     | |
| 8:30 AM - 9:30 AM    | Public Data Resources                       | [Steve Reed](reed.html), [Megan Sweitzer](sweitzer.html), and [Ana Aizcorbe](aizcorbe.html) |
| 9:30 AM - 9:45 AM    | Break                                       | |
| 9:45 AM - 10:45 AM   | Private Data Collection and Research        | [Catherine Cullinane-Thomas](thomas.html), [Mary Muth](muth.html), [Leo Feler](feler.html), and [Doug Edmonds](edmonds.html) |
| 10:45 AM - 12:00 PM  | Breakout Sessions                           | [Ana Aizcorbe](aizcorbe.html), [John Baffes](baffes.html), [Jude Bayham](bayham.html), [Anne Byrne](byrne.html), [Metin Çakir](cakir.html), [Kailin Kroetz](kroetz.html), [James MacDonald](macdonald.html), [Matthew Maclachlan](maclachlan.html), [Abigail Okrent](okrent.html), [Aaron Smith](smith.html), [Simon Somogyi](somogyi.html), [Chen Zhen](zhen.html) |
| 12:00 PM - 12:30 PM  | Closing Remarks                             | |
-->



<!-- ################## -->

<div style="padding-bottom: 60px;"></div>

<!--===================================-->
<div style="text-align: center;">
  <a href="index.html" class="btn" style="background-color: black; color: white; padding: 10px 20px; text-align: center; text-decoration: none; display: inline-block;">Back to Home</a>
</div>



